name: evosplit
channels:
  - conda-forge
  - bioconda
  - schrodinger
dependencies:
  - python=3.10
  - pymol-bundle
  - pip
  - hmmer==3.3.2
  - hhsuite==3.3.0
  - pip:
      - torch==2.8.0 --extra-index-url https://download.pytorch.org/whl/cu126
      - biopython==1.83
      - deepspeed
      - dm-tree==0.1.8
      - ml-collections
      - numpy==1.26.3
      - pandas==2.2.0
      - scikit-learn==1.7.2
      - PyYAML
      - requests
      - scipy==1.12.0
      - matplotlib==3.8.2
      - seaborn==0.13.2
      - tqdm==4.64.0
      - typing-extensions==4.15.0
      - pytorch_lightning==2.3.1
      - setuptools==80.9.0
      - wandb
      - einops
      - fairscale
      - omegaconf
      - hydra-core
      - pytest
      - git+https://github.com/NVIDIA/dllogger.git